server:
  port: 8080
security:
  user:
    password: user  # 直接登录时的密码
  ignored: /
  sessions: never   # session策略

  oauth2:
    sso:
      loginPath: /login   # 登录路径
    client:
      clientId: dec027c4d1abbbf727c8
      clientSecret: 23ddbe1711bbc9e141e45ff51ab3270de8ae1c9d
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false
